version: '3'

services:
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/master/data:/var/lib/mysql
      - ./mysql/master/conf:/etc/mysql/conf.d
    networks:
      - mysql_network

  mysql_slave1:
    image: mysql:8.0
    container_name: mysql_slave1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/slave1/data:/var/lib/mysql
      - ./mysql/slave1/conf:/etc/mysql/conf.d
    networks:
      - mysql_network
    depends_on:
      - mysql_master

  mysql_slave2:
    image: mysql:8.0
    container_name: mysql_slave2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/slave2/data:/var/lib/mysql
      - ./mysql/slave2/conf:/etc/mysql/conf.d
    networks:
      - mysql_network
    depends_on:
      - mysql_master

networks:
  mysql_network:
    driver: bridge 